"""extend medical history and add is_active to allergies conditions

Revision ID: 12431a907aea
Revises: c032b78c22f4
Create Date: 2026-08-07 20:47:28.573256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '12431a907aea'
down_revision: Union[str, None] = 'c032b78c22f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated) so this is safe to run
    # against a table that already has rows, matching the model-side default.
    op.add_column(
        'patient_allergies',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'patient_conditions',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column('patient_medical_histories', sa.Column('author_user_id', sa.Uuid(), nullable=False))
    op.add_column(
        'patient_medical_histories',
        sa.Column('is_finalized', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('patient_medical_histories', sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patient_medical_histories', sa.Column('amends_entry_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'patient_medical_histories', 'patient_medical_histories', ['amends_entry_id'], ['id'])
    op.drop_column('patient_medical_histories', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_medical_histories', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'patient_medical_histories', type_='foreignkey')
    op.drop_column('patient_medical_histories', 'amends_entry_id')
    op.drop_column('patient_medical_histories', 'finalized_at')
    op.drop_column('patient_medical_histories', 'is_finalized')
    op.drop_column('patient_medical_histories', 'author_user_id')
    op.drop_column('patient_conditions', 'is_active')
    op.drop_column('patient_allergies', 'is_active')
    # ### end Alembic commands ###
