"""add failure reason to notification messages

Revision ID: 8d569bbaea97
Revises: b30f15349c35
Create Date: 2026-08-02 11:36:06.992055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d569bbaea97'
down_revision: Union[str, None] = 'b30f15349c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_messages', sa.Column('failure_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_messages', 'failure_reason')
    # ### end Alembic commands ###
