"""add versioning and invalidation fields to consent documents

Revision ID: b19f9d8c36b4
Revises: 12431a907aea
Create Date: 2026-08-08 08:34:00.268176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b19f9d8c36b4'
down_revision: Union[str, None] = '12431a907aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated): every existing row
    # predates versioning/regeneration, so each one is trivially its own
    # (only, therefore current) version.
    op.add_column(
        'consent_documents',
        sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column('consent_documents', sa.Column('regenerated_reason', sa.String(), nullable=True))
    op.add_column('consent_documents', sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consent_documents', sa.Column('invalidated_reason', sa.String(), nullable=True))
    op.add_column('consent_documents', sa.Column('invalidated_by_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_consent_documents_submission_id'), 'consent_documents', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_documents_submission_id'), table_name='consent_documents')
    op.drop_column('consent_documents', 'invalidated_by_user_id')
    op.drop_column('consent_documents', 'invalidated_reason')
    op.drop_column('consent_documents', 'invalidated_at')
    op.drop_column('consent_documents', 'regenerated_reason')
    op.drop_column('consent_documents', 'is_current')
    # ### end Alembic commands ###
