"""add booking_requests table

Revision ID: c032b78c22f4
Revises: fbae6f06d123
Create Date: 2026-08-02 13:36:45.120272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c032b78c22f4'
down_revision: Union[str, None] = 'fbae6f06d123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_requests',
    sa.Column('treatment_definition_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'SCHEDULED', 'DECLINED', name='bookingrequeststatus'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_definition_id'], ['treatment_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_requests_organization_id'), 'booking_requests', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_requests_organization_id'), table_name='booking_requests')
    op.drop_table('booking_requests')
    # ### end Alembic commands ###
