"""add audit event sequence and fix clinical note finalized_at timezone

Revision ID: fbae6f06d123
Revises: 8d569bbaea97
Create Date: 2026-08-02 13:24:25.271162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fbae6f06d123'
down_revision: Union[str, None] = '8d569bbaea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False))
    op.create_unique_constraint(None, 'audit_events', ['sequence'])
    op.alter_column('clinical_notes', 'finalized_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_notes', 'finalized_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'audit_events', type_='unique')
    op.drop_column('audit_events', 'sequence')
    # ### end Alembic commands ###
